import numpy as np


def get_loss_from_ray(path):
    """Read and return a list of loss from 'result.json' generated by Ray.Tune

    :param path: The pat of 'result.json'
    :return: A list of loss
    """

    losses = []
    with open(path, 'r') as f:
        for line in f.readlines():
            loss = float(line.split(',')[0].split(':')[1][1:])
            losses.append(loss)

    return losses


def plot_truth(lengths, trajectories, viz):
    for i in range(len(lengths)):
        win = str(i)
        timeline = np.arange(lengths[i] + 1)
        trajectories[i].insert(0, 0.0)
        viz.line(X=timeline, Y=trajectories[i],
                 win=win, name='truth',
                 opts=dict(title=win, legend=['truth'], showlegend=True))

